name: level2

on:
  workflow_dispatch:    #workflow dispatch means we can normally triggered

jobs:          # if we declared in jobs level env variables os we can acess one job to 2 job so that i can see in job 2 
  level1:
    runs-on: ubuntu-latest

    env:
      CITY: Hyderabad     
      TRAINER: Chaithanya

    steps:
      - name: level2
        env:
          CITY: Hyderabad
          TRAINER: Chaitanya
        run: |
          echo "welcome to $CITY"
          echo "your trainer is $TRAINER"

      - name: next steps
        run: echo "city is $CITY and trainer is $TRAINER"
