name: level3

on:
  workflow_dispatch:   # if we delclared in workflow level env any job or any step
env:
  CITY: hyderabad/mumbai
  TRAINER: chaithanya/ch

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: level3
        env:
          CITY: Hyderabad
        run: |
          echo "welcome to $CITY"
          
      - name: job2
        run: echo " trainer is $TRAINER"
